"""
This type stub file was generated by pyright.
"""

_SUPPORTED_COMPRESSORS = set(["snappy", "zlib", "zstd"])
_NO_COMPRESSION = set(['ismaster'])
def validate_compressors(dummy, value):
    ...

def validate_zlib_compression_level(option, value):
    ...

class CompressionSettings(object):
    def __init__(self, compressors, zlib_compression_level):
        self.compressors = ...
        self.zlib_compression_level = ...
    
    def get_compression_context(self, compressors):
        ...
    


def _zlib_no_compress(data):
    """Compress data with zlib level 0."""
    ...

class SnappyContext(object):
    compressor_id = ...
    @staticmethod
    def compress(data):
        ...
    


class ZlibContext(object):
    compressor_id = ...
    def __init__(self, level):
        ...
    


class ZstdContext(object):
    compressor_id = ...
    @staticmethod
    def compress(data):
        ...
    


def decompress(data, compressor_id):
    ...

