"""
This type stub file was generated by pyright.
"""

import os
import sys

"""Support for spawning a daemon process.

PyMongo only attempts to spawn the mongocryptd daemon process when automatic
client-side field level encryption is enabled. See
:ref:`automatic-client-side-encryption` for more info.
"""
_WAIT_TIMEOUT = 10
_THIS_FILE = os.path.realpath(__file__)
if sys.version_info[0] < 3:
    ...
else:
    def _popen_wait(popen, timeout):
        """Implement wait timeout support for Python 3."""
        ...
    
def _silence_resource_warning(popen):
    """Silence Popen's ResourceWarning.

    Note this should only be used if the process was created as a daemon.
    """
    ...

if sys.platform == 'win32':
    ...
else:
    def _spawn(args):
        """Spawn the process and silence stdout/stderr."""
        ...
    
    def _spawn_daemon_double_popen(args):
        """Spawn a daemon process using a double subprocess.Popen."""
        ...
    
    def _spawn_daemon(args):
        """Spawn a daemon process (Unix)."""
        ...
    
