"""
This type stub file was generated by pyright.
"""

from bson.py3compat import PY3
from typing import Any, Optional

"""Support for resolving hosts and options from mongodb+srv:// URIs."""
if PY3:
    def maybe_decode(text):
        ...
    
else:
    def maybe_decode(text):
        ...
    
class _SrvResolver(object):
    def __init__(self, fqdn, connect_timeout: Optional[Any] = ...):
        ...
    
    def get_options(self):
        ...
    
    def _resolve_uri(self, encapsulate_errors):
        ...
    
    def _get_srv_response_and_hosts(self, encapsulate_errors):
        ...
    
    def get_hosts(self):
        ...
    
    def get_hosts_and_min_ttl(self):
        ...
    


