"""
This type stub file was generated by pyright.
"""

import sys
import threading

"""Support for SSL in PyMongo."""
HAVE_SSL = True
HAVE_CERTIFI = False
HAVE_WINCERTSTORE = False
_WINCERTSLOCK = threading.Lock()
_WINCERTS = None
_PY37PLUS = sys.version_info[: 2] >= (3, 7)
if HAVE_SSL:
    def validate_cert_reqs(option, value):
        """Validate the cert reqs are valid. It must be None or one of the
        three values ``ssl.CERT_NONE``, ``ssl.CERT_OPTIONAL`` or
        ``ssl.CERT_REQUIRED``.
        """
        ...
    
    def validate_allow_invalid_certs(option, value):
        """Validate the option to allow invalid certificates is valid."""
        ...
    
    def _load_wincerts():
        """Set _WINCERTS to an instance of wincertstore.Certfile."""
        ...
    
    def get_ssl_context(*args):
        """Create and return an SSLContext object."""
        ...
    
else:
    def validate_cert_reqs(option, dummy):
        """No ssl module, raise ConfigurationError."""
        ...
    
    def validate_allow_invalid_certs(option, dummy):
        """No ssl module, raise ConfigurationError."""
        ...
    
    def get_ssl_context(*dummy):
        """No ssl module, raise ConfigurationError."""
        ...
    
